version: '3.8'
services:
  bot:
    build: .
    image: viikkotiedotebot:latest
    volumes:
      - ./logs:/bot/logs:rw
    environment:
      - TIEDOTE_BOT_TOKEN=${TIEDOTE_BOT_TOKEN}
      - TIEDOTE_BOT_ADMINS=${TIEDOTE_BOT_ADMINS}